# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AchWay', models.CharField(max_length=50)),
                ('ins_dt', models.DateTimeField(auto_now_add=True)),
                ('upd_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_goal', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=30)),
                ('ins_dt', models.DateTimeField(auto_now_add=True)),
                ('upd_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_goal', models.CharField(max_length=30)),
                ('ins_dt', models.DateTimeField(auto_now_add=True)),
                ('upd_dt', models.DateTimeField(auto_now=True)),
                ('main_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.MainGoal')),
            ],
        ),
        migrations.AddField(
            model_name='achway',
            name='sub_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.SubGoal'),
        ),
    ]
