# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20171211_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achway',
            old_name='ach_Way',
            new_name='ach_way',
        ),
    ]
