# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20171211_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='sub_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
