# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_subgoal_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='achway',
            name='sub_id',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
